### ISSUE TITLE
Can't harvest Beetroot with the hoe.

### ISSUE THREAD

**Issue by PadreJesus** [sammyt291/FineHarvest#2]
Does not work with beetroot plantations.

**Comment by N1ghthauq** [comment]
I am having this issue too.

**Comment by Nobookie** [comment]
@PadreJesus @N1ghthauq Fixed: [https://github.com/leothawne/FineHarvest/releases/tag/v1.4.6](https://github.com/leothawne/FineHarvest/releases/tag/v1.4.6)

**Comment by sammyt291** [comment]
Merged above fix in the latest version (1.4.7)
